# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/DEMO/DEMO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO || ORIG_REF_NAME==DEMO} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_processing_system7_0_0 || ORIG_REF_NAME==DEMO_processing_system7_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_0 || ORIG_REF_NAME==DEMO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xbar_0 || ORIG_REF_NAME==DEMO_xbar_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ps7_0_axi_periph_0/DEMO_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ps7_0_axi_periph_0 || ORIG_REF_NAME==DEMO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_iic_0_1 || ORIG_REF_NAME==DEMO_axi_iic_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_traffic_gen_0_0/DEMO_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_traffic_gen_0_0 || ORIG_REF_NAME==DEMO_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_traffic_gen_1_0/DEMO_axi_traffic_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_traffic_gen_1_0 || ORIG_REF_NAME==DEMO_axi_traffic_gen_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_0_0/DEMO_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_0_0 || ORIG_REF_NAME==DEMO_vio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rgb_rainbow_0_3/DEMO_rgb_rainbow_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rgb_rainbow_0_3 || ORIG_REF_NAME==DEMO_rgb_rainbow_0_3} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_smc_4/DEMO_axi_smc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_smc_4 || ORIG_REF_NAME==DEMO_axi_smc_4} -quiet] -quiet

# Block Designs: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/bd_2e8b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_0/bd_2e8b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_1/bd_2e8b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_2/bd_2e8b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_3/bd_2e8b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_4/bd_2e8b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_5/bd_2e8b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_6/bd_2e8b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_7/bd_2e8b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_8/bd_2e8b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_9/bd_2e8b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_10/bd_2e8b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_11/bd_2e8b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_12/bd_2e8b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rst_clk_125M_2 || ORIG_REF_NAME==DEMO_rst_clk_125M_2} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/DEMO_axi_smc_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_smc_1_3 || ORIG_REF_NAME==DEMO_axi_smc_1_3} -quiet] -quiet

# Block Designs: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/bd_088f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_0/bd_088f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_1/bd_088f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_2/bd_088f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_3/bd_088f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_4/bd_088f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_5/bd_088f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_6/bd_088f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_7/bd_088f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_8/bd_088f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_9/bd_088f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_10/bd_088f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_11/bd_088f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_12/bd_088f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/DEMO/ip/DEMO_rgb_controller_0_0/DEMO_rgb_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rgb_controller_0_0 || ORIG_REF_NAME==DEMO_rgb_controller_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_1_0/DEMO_vio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_1_0 || ORIG_REF_NAME==DEMO_vio_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_2_0/DEMO_vio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_2_0 || ORIG_REF_NAME==DEMO_vio_2_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ila_0_0/DEMO_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ila_0_0 || ORIG_REF_NAME==DEMO_ila_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_debouncer_0_0/DEMO_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_debouncer_0_0 || ORIG_REF_NAME==DEMO_debouncer_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_state_machine_0_1/DEMO_state_machine_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_state_machine_0_1 || ORIG_REF_NAME==DEMO_state_machine_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_timer_0_0/DEMO_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_0_0 || ORIG_REF_NAME==DEMO_axi_timer_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xlconcat_0_0/DEMO_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xlconcat_0_0 || ORIG_REF_NAME==DEMO_xlconcat_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_timer_1_0/DEMO_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_1_0 || ORIG_REF_NAME==DEMO_axi_timer_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_1_0 || ORIG_REF_NAME==DEMO_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_BuzzerBooster_Driver_0_1/DEMO_BuzzerBooster_Driver_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_BuzzerBooster_Driver_0_1 || ORIG_REF_NAME==DEMO_BuzzerBooster_Driver_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_auto_pc_0/DEMO_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_auto_pc_0 || ORIG_REF_NAME==DEMO_auto_pc_0} -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_processing_system7_0_0 || ORIG_REF_NAME==DEMO_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_0 || ORIG_REF_NAME==DEMO_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_0 || ORIG_REF_NAME==DEMO_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_iic_0_1 || ORIG_REF_NAME==DEMO_axi_iic_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_traffic_gen_1_0/DEMO_axi_traffic_gen_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_traffic_gen_1_0 || ORIG_REF_NAME==DEMO_axi_traffic_gen_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_vio_0_0/DEMO_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_0_0 || ORIG_REF_NAME==DEMO_vio_0_0} -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_1/bd_2e8b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_1/bd_2e8b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_5/bd_2e8b_s00a2s_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_6/bd_2e8b_sarn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_7/bd_2e8b_srn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_8/bd_2e8b_sawn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_9/bd_2e8b_swn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_10/bd_2e8b_sbn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_11/bd_2e8b_m00s2a_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_4/ooc.xdc

# XDC: bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_rst_clk_125M_2 || ORIG_REF_NAME==DEMO_rst_clk_125M_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_rst_clk_125M_2 || ORIG_REF_NAME==DEMO_rst_clk_125M_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_1/bd_088f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_1/bd_088f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_5/bd_088f_s00a2s_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_6/bd_088f_sarn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_7/bd_088f_srn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_8/bd_088f_sawn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_9/bd_088f_swn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_10/bd_088f_sbn_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_11/bd_088f_m00s2a_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_smc_1_3/ooc.xdc

# XDC: bd/DEMO/ip/DEMO_vio_1_0/DEMO_vio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_1_0 || ORIG_REF_NAME==DEMO_vio_1_0} -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_vio_2_0/DEMO_vio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_2_0 || ORIG_REF_NAME==DEMO_vio_2_0} -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_ila_0_0 || ORIG_REF_NAME==DEMO_ila_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_ila_0_0 || ORIG_REF_NAME==DEMO_ila_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_ila_0_0/DEMO_ila_0_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_timer_0_0/DEMO_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_0_0 || ORIG_REF_NAME==DEMO_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_timer_0_0/DEMO_axi_timer_0_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_timer_1_0/DEMO_axi_timer_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_timer_1_0 || ORIG_REF_NAME==DEMO_axi_timer_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_timer_1_0/DEMO_axi_timer_1_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_1_0 || ORIG_REF_NAME==DEMO_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_ooc.xdc

# XDC: bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_1_0 || ORIG_REF_NAME==DEMO_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DEMO/ip/DEMO_auto_pc_0/DEMO_auto_pc_0_ooc.xdc

# XDC: bd/DEMO/DEMO_ooc.xdc
