#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : DEMO.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Nov 10 00:02:58 -0300 2025
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: DEMO.sh [-help]
# usage: DEMO.sh [-lib_map_path]
# usage: DEMO.sh [-noclean_files]
# usage: DEMO.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'DEMO.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm dist_mem_gen_v8_0_13 lib_pkg_v1_0_2 lib_cdc_v1_0_2 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_quad_spi_v3_2_20 xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_7 processing_system7_vip_v1_0_9 axi_gpio_v2_0_23 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_21 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 proc_sys_reset_v5_0_13 axi_iic_v2_0_24 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 axi_traffic_gen_v3_0_7 xlconstant_v1_1_7 smartconnect_v1_0 axi_timer_v2_0_23 xlconcat_v2_1_3 axi_protocol_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "DEMO.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_20 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1735/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_quad_spi_0_0/sim/DEMO_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_9 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_processing_system7_0_0/sim/DEMO_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_gpio_0_0/sim/DEMO_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_xbar_0/sim/DEMO_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/sim/DEMO_rst_ps7_0_50M_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_quad_spi_1_0/sim/DEMO_axi_quad_spi_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/d1e4/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_iic_0_1/sim/DEMO_axi_iic_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_traffic_gen_v3_0_7 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/axi_traffic_gen_v3_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_traffic_gen_v3_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/axi_traffic_gen_v3_0_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_traffic_gen_0_0/sim/DEMO_axi_traffic_gen_0_0.v" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_traffic_gen_1_0/sim/DEMO_axi_traffic_gen_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_vio_0_0/sim/DEMO_vio_0_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/25d7/hdl/rgb_rainbow_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/25d7/hdl/rgb_rainbow_v1_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_rgb_rainbow_0_3/sim/DEMO_rgb_rainbow_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/sim/bd_2e8b.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_0/sim/bd_2e8b_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_1/sim/bd_2e8b_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/053f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_2/sim/bd_2e8b_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_3/sim/bd_2e8b_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/9d43/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_4/sim/bd_2e8b_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_5/sim/bd_2e8b_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_6/sim/bd_2e8b_sarn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_7/sim/bd_2e8b_srn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_8/sim/bd_2e8b_sawn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_9/sim/bd_2e8b_swn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_10/sim/bd_2e8b_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_11/sim/bd_2e8b_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/7af8/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/bd_0/ip/ip_12/sim/bd_2e8b_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_4/sim/DEMO_axi_smc_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_rst_clk_125M_2/sim/DEMO_rst_clk_125M_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/sim/bd_088f.v" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_0/sim/bd_088f_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_1/sim/bd_088f_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_2/sim/bd_088f_s00mmu_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_3/sim/bd_088f_s00tr_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_4/sim/bd_088f_s00sic_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_5/sim/bd_088f_s00a2s_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_6/sim/bd_088f_sarn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_7/sim/bd_088f_srn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_8/sim/bd_088f_sawn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_9/sim/bd_088f_swn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_10/sim/bd_088f_sbn_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_11/sim/bd_088f_m00s2a_0.sv" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/bd_0/ip/ip_12/sim/bd_088f_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_smc_1_3/sim/DEMO_axi_smc_1_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ipshared/4056/src/rgb_controller.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_rgb_controller_0_0/sim/DEMO_rgb_controller_0_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_vio_1_0/sim/DEMO_vio_1_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_vio_2_0/sim/DEMO_vio_2_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_ila_0_0/sim/DEMO_ila_0_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/84ec/Debouncer.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_debouncer_0_0/sim/DEMO_debouncer_0_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/f1fe/src/state_machine.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_state_machine_0_1/sim/DEMO_state_machine_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/eb71/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_timer_0_0/sim/DEMO_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_xlconcat_0_0/sim/DEMO_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_timer_1_0/sim/DEMO_axi_timer_1_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_axi_gpio_1_0/sim/DEMO_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/fd3b/src/BuzzerBooster_Driver_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/DEMO/ipshared/fd3b/src/BuzzerBooster_Driver_v1_0.vhd" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_BuzzerBooster_Driver_0_1/sim/DEMO_BuzzerBooster_Driver_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/f2df/hdl/src/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/4676/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/46fd/hdl" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../Avancefinal.srcs/sources_1/bd/DEMO/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/DEMO/ip/DEMO_auto_pc_0/sim/DEMO_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/DEMO/sim/DEMO.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.DEMO xil_defaultlib.glbl -o DEMO_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./DEMO_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./DEMO.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key DEMO_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc DEMO_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./DEMO.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: DEMO.sh [-help]\n\
Usage: DEMO.sh [-lib_map_path]\n\
Usage: DEMO.sh [-reset_run]\n\
Usage: DEMO.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
